title: 'Actividad econ√≥mica'
default_lang: es
author:
  name: 'Luis Mayta'
  email: luis.mayta@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
